project:
  type: website

execute:
  freeze: auto

website:
  title: "The Data Sketchbook"
  favicon: "favicon.ico"
  google-analytics: 'G-4BTEYBVWPE'
  site-url: https://www.datasketchbook.com
  repo-url: https://github.com/sequentialrant/datasketchbook
  navbar:
    logo: "favicon.ico"
    right:
      # - about.qmd
      - icon: github
        href: https://github.com/sequentialrant
      - icon: twitter
        href: https://twitter.com/sequentialrant
open-graph: true
# site-url: "https://datasketchbook.dev/"
# repo-url: https://github.com/sequentialrant/datasketchbook

format:
  html:
    theme:
      # light: [solarized-light, custom.scss]
      # - solarized-light
      # - html/styles.scss
      # - cosmo
      # - brand
    # css: styles.css
      light:
        - litera
        - custom.scss
      dark:
        - darkly
        - custom.scss
    toc: true
    smooth-scroll: true



